### ISSUE TITLE
On android when app is killed/closed, library events are not triggering

### ISSUE THREAD

**Issue by ARazaAnjum** [infobip/mobile-messaging-react-native-plugin#4]
Below I've pasted my snippet for initializing the SDK and registering the notificationTapped event.
SDK is initializing properly and device is also getting register on infobip portal. 
When sending the push from portal and receiving on android device, after tapping the notification 
**notificationTapped** library event won't trigger in android.

import { mobileMessaging } from 'infobip-mobile-messaging-react-native-plugin';
  mobileMessaging.init(
      {
        applicationCode: Config.INFOBIP_KEY,
        ios: {
          notificationTypes: ['alert', 'badge', 'sound'],
        },
      },
      () => {
            console.log('MobileMessaging started');
      },
      error => {
            console.log('MobileMessaging error: ', error);
      }
    );

    mobileMessaging.register('registrationUpdated', message => {
            console.log('Event received', message);
    })
    mobileMessaging.register("notificationTapped", message => {
      alert(message.body)
    });

**Comment by riskpp** [comment]
@ARazaAnjum 
We've noticed the issue with `notificationTapped` event in case when app is killed by the system and it's fixed in [2.0.4 plugin version](https://github.com/infobip/mobile-messaging-react-native-plugin/releases/tag/2.0.4)

JFYI - If application is killed by the user it will not receive push notification, it's normal behaviour for Android

Please, please check it and notify us if there are no more issues.
