### ISSUE TITLE
messageReceived Library Event on iOS Devices Not Triggering

### ISSUE THREAD

**Issue by moustafadevrn** [infobip/mobile-messaging-react-native-plugin#72]
**Description:**
The messageReceived library event works successfully on Android devices but does not trigger on iOS devices. This inconsistency needs to be addressed to ensure the functionality is consistent across both platforms.

**Steps to Reproduce:**
Implement the messageReceived event in the app.
Trigger an event that should activate messageReceived.
Observe the behavior on Android and iOS devices.

**Expected Behavior:**
The messageReceived event should trigger consistently on both Android and iOS devices.

**Actual Behavior:**
The event triggers as expected on Android devices but does not trigger on iOS devices.

**Comment by moustafadevrn** [comment]
Hello @fortesdev Thank you for your suggestion. I actually tried the same line of code you mentioned . However, the event is not triggered as you suggested.

As I mentioned before, the notification is not received while the app is in the foreground.

**Comment by fortesdev** [comment]
Hi @moustafadevrn,

I wrote that "I added" that line of code (that you can write as well, not to search for it), in line 11 [here](https://github.com/infobip/mobile-messaging-react-native-plugin/blob/master/Example/screens/HomeScreen.js). 

And it works on my testing:
App in foreground, broadcasting regular push => event received (notification not visible as it is silent)
App in foreground, chat message received, but chat not present => event received (notification visible)
App in foreground, chat message received, but chat present => event and notification **not** received by design, as explained [here.](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/In%E2%80%90app-chat#chat-and-push-notifications)

If you still face issues, feel free to check/share [MobileMessaging] console logs (excluding your ids/secrets), but also test with our Example if possible.

**Comment by riskpp** [comment]
I'll close the issue due to inactivity, feel free to reopen it if needed.
