### ISSUE TITLE
Will it work for RN 0.61.3 !?

### ISSUE THREAD

**Issue by PavanApollo** [infobip/mobile-messaging-react-native-plugin#8]
Hi I just wanted to know before integrating this fantastic library that if this library works on RN 0.61.3. Since in ReadMe file, it shows React Native - 0.61.5 is the minimum requirement !?

Prompt reply can be expected. @riskpp

**Comment by tjuric** [comment]
Hi @PavanApollo,
We have stated that min required version is 0.61.5 because that was actually the minimal tested version. However, as checked, patch versions of RN should not break any of our functionalities and you can safely use versions 0.61.0+. We're going to change it in our readme file.

BR,
Tereza
